### ISSUE TITLE
pip install not working on ubuntu 20.04

### ISSUE THREAD

**Issue by tintin10q** [jonashaag/bjoern#233]
```
$ pip install bjoern
Defaulting to user installation because normal site-packages is not writeable
Collecting bjoern
  Using cached bjoern-3.2.1.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: bjoern
  Building wheel for bjoern (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.11
      copying bjoern.py -> build/lib.linux-x86_64-3.11
      running build_ext
      building '_bjoern' extension
      creating build/temp.linux-x86_64-3.11
      creating build/temp.linux-x86_64-3.11/bjoern
      creating build/temp.linux-x86_64-3.11/http-parser
      x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DSIGNAL_CHECK_INTERVAL=0.1 -DWANT_SIGNAL_HANDLING=yes -DWANT_SIGINT_HANDLING=yes -Ihttp-parser -Istatsd-c-client -I/usr/include/libev -I/opt/local/include -I/usr/include/python3.11 -I/usr/local/include/python3.11 -c bjoern/_bjoernmodule.c -o build/temp.linux-x86_64-3.11/bjoern/_bjoernmodule.o -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g
      bjoern/_bjoernmodule.c:1:10: fatal error: Python.h: No such file or directory
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bjoern
  Running setup.py clean for bjoern
Failed to build bjoern
Installing collected packages: bjoern
  Running setup.py install for bjoern ... error
  error: subprocess-exited-with-error

  × Running setup.py install for bjoern did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.11
      copying bjoern.py -> build/lib.linux-x86_64-3.11
      running build_ext
      building '_bjoern' extension
      creating build/temp.linux-x86_64-3.11
      creating build/temp.linux-x86_64-3.11/bjoern
      creating build/temp.linux-x86_64-3.11/http-parser
      x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DSIGNAL_CHECK_INTERVAL=0.1 -DWANT_SIGNAL_HANDLING=yes -DWANT_SIGINT_HANDLING=yes -Ihttp-parser -Istatsd-c-client -I/usr/include/libev -I/opt/local/include -I/usr/include/python3.11 -I/usr/local/include/python3.11 -c bjoern/_bjoernmodule.c -o build/temp.linux-x86_64-3.11/bjoern/_bjoernmodule.o -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g
      bjoern/_bjoernmodule.c:1:10: fatal error: Python.h: No such file or directory
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> bjoern

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by tintin10q** [comment]
I installed the dependencies with `sudo apt-get install python3-dev libev-dev`

**Comment by tintin10q** [comment]
Does it not work with python 3.11?

**Comment by jonashaag** [comment]
Should work, can you try to locate the `Python.h` file on your computer?

Eg by `find /usr | grep Python.h`

**Comment by tintin10q** [comment]
That gave me this `/usr/include/python3.8/Python.h`

So it seems to have installed  python3-dev for python3.8 however when I just use the python command it gives me python 3.11. Do you know how I can install python3-dev for python3.11?

**Comment by tintin10q** [comment]
Ok it seems you can just specify a version like this: `sudo apt install python3.11-dev`

After running that command it worked for me. Maybe you should add this to the install docs. With that usefull grep command as well.
